framework:
    workflows:
        comment:
            type: state_machine
            audit_trail:
                enabled: "%kernel.debug%"
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Comment
            initial_marking: submitted
            places:
                - submitted
                - ham
                - rejected
                - published
            transitions:
                accept:
                    from: submitted
                    to: ham
                publish_ham:
                    from: ham
                    to: published
                reject_ham:
                    from: ham
                    to: rejected